# Generated by Django 5.2 on 2025-04-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='supporter',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_used',
        ),
    ]
